name: dart_fusion
description: A library that brings together a harmonious blend of essential
  tools, utilities, and components designed to supercharge your Dart projects.
version: 2.3.0
homepage: https://github.com/Nialixus/dart_fusion.git
funding: https://www.buymeacoffee.com/nialixus
topics: collection

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  args: ^2.4.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^9.0.3
  logger: ^1.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter: null
