name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dart_fusion:
    path: ../../dart_fusion/
  dart_fusion_flutter:
    path: ../
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/translation//
    - assets/image/icon/
    - assets/image/background/
    - assets/image/
    - assets/translation/
    - assets/
  uses-material-design: true