name: example
description: A new Flutter project.
publish_to: 'none'
version: 3.1.4+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dart_fusion_flutter:
    git:
      url: https://github.com/Nialixus/dart_fusion.git
      path: dart_fusion_flutter
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/translation/
    - assets/image/icon/
    - assets/image/background/
    - assets/image/
    - assets/translation/
    - assets/
  uses-material-design: true