name: dart_fusion
description: A library that brings together a harmonious blend of essential
  tools, utilities, and components designed to supercharge your Dart projects.
version: 3.1.7
executables:
  dart_fusion: dart_fusion
homepage: https://BreegBenjamin.dev
repository: https://github.com/BreegBenjamin/dart_fusion.git
issue_tracker: https://github.com/BreegBenjamin/dart_fusion/issues
documentation: https://raw.githack.com/BreegBenjamin/dart_fusion/main/dart_fusion/doc/api/index.html
funding:
  - https://www.buymeacoffee.com/nialixus
screenshots:
  - description: 'Dart Fusion Logo'
    path: ../logo.png
topics:
  - collection
  - utility

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  args: ^2.4.2
  dart_frog: ^1.0.1
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.12.0
  equatable: ^2.0.5
  http: ^1.1.0
  logger: ^2.0.2+1
  
dev_dependencies:
  test: ^1.25.2
