name: dart_fusion
description: A library that brings together a harmonious blend of essential
  tools, utilities, and components designed to supercharge your Dart projects.
version: 3.0.1
homepage: https://inidia.app
repository: https://github.com/Nialixus/dart_fusion.git
issue_tracker: https://github.com/Nialixus/dart_fusion/issues
documentation: https://raw.githack.com/Nialixus/dart_fusion/main/doc/api/index.html
publish_to: none
funding: 
  - https://www.buymeacoffee.com/nialixus
screenshots:
  - description: 'Dart Fusion Logo'
    path: logo.png
topics:
  - collection
  - utility

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  args: ^2.4.2
  dart_frog: ^1.0.1
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.12.0
  equatable: ^2.0.5
  http: ^1.1.0
  logger: ^2.0.2+1
